In [1]:
import pandas as pd
from yahoo_fin.stock_info import get_data

Warning - Certain functionality
             requires requests_html, which is not installed.

             Install using:
             pip install requests_html

             After installation, you may have to restart your Python session.

In [5]:
amazon_weekly= get_data("aapl", start_date="12/04/2009", end_date="12/04/2019", index_as_date = True, interval="1d")
amazon_weekly

,open,high,low,close,adjclose,volume,ticker
2009-12-04,7.132143,7.138571,6.795714,6.904286,5.837245,826884800,AAPL
2009-12-07,6.904286,6.920357,6.738571,6.748214,5.705296,714758800,AAPL
2009-12-08,6.762857,6.869643,6.739286,6.781071,5.733074,690398800,AAPL
2009-12-09,6.831429,7.077143,6.796786,7.064286,5.972520,684782000,AAPL
2009-12-10,7.125000,7.132143,7.004286,7.015357,5.931153,489669600,AAPL
...,...,...,...,...,...,...,...
2019-11-26,66.735001,66.790001,65.625000,66.072502,64.200844,105207600,AAPL
2019-11-27,66.394997,66.995003,66.327499,66.959999,65.063187,65235600,AAPL
2019-11-29,66.650002,67.000000,66.474998,66.812500,64.919884,46617600,AAPL
2019-12-02,66.817497,67.062500,65.862503,66.040001,64.169250,94487200,AAPL
2019-12-03,64.577499,64.882500,64.072502,64.862503,63.025112,114430400,AAPL